clean: true
sdk: iphonesimulator
xcodebuild_arguments:
 - -project
 - Barcode-Data-Matcher.xcodeproj
 - -scheme
 - BarcodeDataMatcher
 - -sdk
 - iphonesimulator
 - -arch
 - x86_64
author: Applied Recognition, Inc.
module: BarcodeDataMatcher
min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
